jobs:
  - job: win
    displayName: Windows
    pool:
      vmImage: "VS2017-Win2016"

    strategy:
      matrix:
        node_8_x:
          node_version: ">=8.12.x"
        node_10_x:
          node_version: "10.x"

    steps:
      - template: win.yml

  - job: linux
    displayName: Linux
    pool:
      vmImage: "ubuntu-16.04"

    strategy:
      matrix:
        node_8_x:
          node_version: ">=8.12.x"
        node_10_x:
          node_version: "10.x"

    steps:
      - template: linux.yml

  - job: mac
    displayName: MacOS
    pool:
      vmImage: "macos-10.13"

    strategy:
      matrix:
        node_8_x:
          node_version: ">=8.12.x"
        node_10_x:
          node_version: "10.x"

    steps:
<<<<<<< HEAD
      - template: mac.yml
=======
- template: mac.yml
>>>>>>> ac319b58a97de1cc5a2a445ffe2c846f646c39a9
